pvc:
  name: mysql-pv-claim
  storageClassName: manual
  accessModes: ReadWriteMany
  resources:
    requests:
      storage: 5Gi

deployment:
  name: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
  container:
    image: mysql:8.0
    name: mysql
    env:
      MYSQL_ROOT_PASSWORD: password
  volumes:
    persistentVolumeClaim:
      claimName: mysql-pv-claim

service:
  name: mysql-service
  type: LoadBalancer
  selector:
    app: mysql
