# by default use release name if not defined (optional)
name: ataraxia

# numbers of pod replicas
replicas: 1

# service configurations
service:
  type: LoadBalancer
  port: 3306
  targetPort: 3306
  protocol: TCP

# rollingUpdate configurations
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 0

# image configurations
image:
  repository: mysql
  tag: 9.0
  pullPolicy: IfNotPresent

# environment 
userPassword: password

# resources configurations
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"