# PVC Values 
pvc:
  name: mysql-pv-claim
  storageClassName: csi-cephfs-sc
  accessModes: ReadWriteMany
  resources:
    requests:
      storage: 5Gi

# Deployment Values 
deployment:
  name: ataraxia
  selector:
    matchLabels:
      app: ataraxia
  template:
    metadata:
      labels:
        app: ataraxia
  container:
    image: mysql:8.0
    name: ataraxia
    env:
      MYSQL_ROOT_PASSWORD: password
  volumes:
    persistentVolumeClaim:
      claimName: mysql-pv-claim

# Service Values
service:
  name: ataraxia
  type: LoadBalancer
  selector:
    app: ataraxia
