apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.custName }}-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.selector.matchLabels.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.template.metadata.labels.app }}
    spec:
      containers:
        - image: {{ .Values.deployment.container.image }}
          name: {{ .Values.deployment.container.name }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.deployment.container.env.MYSQL_ROOT_PASSWORD }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.volumes.persistentVolumeClaim.claimName }}
