apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ataraxia.labels" . | nindent 4 }}
  name: {{ default $.Release.Name $.Values.name }}-deployment
spec:
  replicas: {{ $.Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ $.Values.rollingUpdate.maxSurge }}
      maxUnavailable:  {{ $.Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "ataraxia.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ataraxia.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ default $.Release.Name $.Values.name }}-sa
      containers:
      - image: {{ $Values.image.repository }}:{{ $Values.image.tag }}
        name: ataraxia
        imagePullPolicy: {{ $Values.image.pullPolicy }}
        ports:
        - containerPort: {{ $.Values.service.targetPort }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: {{ $Values.userPassword }}