apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ataraxia.serviceAccountName" . }}
  labels:
    {{- include "ataraxia.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
