apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Values.service.selector.app }}
